# .github/workflows/gitleaks.yaml
name:  DevSecOps - Secret Scanner (Gitleaks)


on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  secret_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Code and History
        uses: actions/checkout@v4
        with:
          fetch-depth: 0 
          
      - name:  Run Gitleaks Scan (OSS SAST)
        uses: zricethezav/gitleaks-action@v2
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

        continue-on-error: true